[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
proof_of_wake = "3XY5vp1p4Q9fCeCwQNz3yMikYZhoXFJDDmEp6dBXMpx4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/ubuntu/.openclaw/workspace/deployment-wallet.json"

[scripts]
test = "npm run test"
